name: Snake Game

on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create index.html for Snake Game
      run: |
        mkdir -p public
        echo '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jogo da Cobrinha</title>
    <style>
        body {
            background-color: #000;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        canvas {
            border: 1px solid #fff;
        }
    </style>
</head>
<body>
    <canvas id="gameCanvas" width="400" height="400"></canvas>
    <script>
        const canvas = document.getElementById("gameCanvas");
        const ctx = canvas.getContext("2d");

        const box = 20;
        const canvasSize = canvas.width;

        let snake = [];
        snake[0] = { x: 9 * box, y: 10 * box };

        let direction;
        let food = {
            x: Math.floor(Math.random() * 19 + 1) * box,
            y: Math.floor(Math.random() * 19 + 1) * box
        };

        document.addEventListener("keydown", directionControl);

        function directionControl(event) {
            if (event.keyCode === 37 && direction !== "RIGHT") {
                direction = "LEFT";
            } else if (event.keyCode === 38 && direction !== "DOWN") {
                direction = "UP";
            } else if (event.keyCode === 39 && direction !== "LEFT") {
                direction = "RIGHT";
            } else if (event.keyCode === 40 && direction !== "UP") {
                direction = "DOWN";
            }
        }

        function collision(newHead, array) {
            for (let i = 0; i < array.length; i++) {
                if (newHead.x === array[i].x && newHead.y === array[i].y) {
                    return true;
                }
            }
            return false;
        }

        function draw() {
            ctx.fillStyle = "#000";
            ctx.fillRect(0, 0, canvasSize, canvasSize);

            for (let i = 0; i < snake.length; i++) {
                ctx.fillStyle = i === 0 ? "#fff" : "#0f0";
                ctx.fillRect(snake[i].x, snake[i].y, box, box);
                ctx.strokeStyle = "#000";
                ctx.strokeRect(snake[i].x, snake[i].y, box, box);
            }

            ctx.fillStyle = "#f00";
            ctx.fillRect(food.x, food.y, box, box);

            let snakeX = snake[0].x;
            let snakeY = snake[0].y;

            if (direction === "LEFT") snakeX -= box;
            if (direction === "UP") snakeY -= box;
            if (direction === "RIGHT") snakeX += box;
            if (direction === "DOWN") snakeY += box;

            if (snakeX === food.x && snakeY === food.y) {
                food = {
                    x: Math.floor(Math.random() * 19 + 1) * box,
                    y: Math.floor(Math.random() * 19 + 1) * box
                };
            } else {
                snake.pop();
            }

            let newHead = {
                x: snakeX,
                y: snakeY
            };

            if (snakeX < 0 || snakeX >= canvasSize || snakeY < 0 || snakeY >= canvasSize || collision(newHead, snake)) {
                clearInterval(game);
            }

            snake.unshift(newHead);
        }

        let game = setInterval(draw, 100);
    </script>
</body>
</html>' > public/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
